CREATE TABLE [stg_survey_monkey].[survey_monkey_enriched] (
    [First Name]                  VARCHAR (MAX) NULL,
    [Last Name]                   VARCHAR (MAX) NULL,
    [Email Address]               VARCHAR (MAX) NULL,
    [Job Title]                   VARCHAR (MAX) NULL,
    [Company Name]                VARCHAR (MAX) NULL,
    [Country]                     VARCHAR (MAX) NULL,
    [Comments]                    VARCHAR (MAX) NULL,
    [Position]                    VARCHAR (MAX) NULL,
    [Area of Activity]            VARCHAR (MAX) NULL,
    [Primary Market of Operation] VARCHAR (MAX) NULL,
    [Company Revenue]             VARCHAR (MAX) NULL,
    [Subscription Options]        VARCHAR (MAX) NULL,
    [Internal Coding]             VARCHAR (MAX) NULL,
    [Phone]                       VARCHAR (MAX) NULL,
    [Site Subscriber]             VARCHAR (MAX) NULL,
    [Geographies]                 FLOAT (53)    NULL,
    [MEMBER_RATING]               BIGINT        NULL,
    [OPTIN_TIME]                  DATETIME      NULL,
    [OPTIN_IP]                    FLOAT (53)    NULL,
    [CONFIRM_TIME]                DATETIME      NULL,
    [CONFIRM_IP]                  VARCHAR (MAX) NULL,
    [LATITUDE]                    VARCHAR (MAX) NULL,
    [LONGITUDE]                   VARCHAR (MAX) NULL,
    [GMTOFF]                      VARCHAR (MAX) NULL,
    [DSTOFF]                      VARCHAR (MAX) NULL,
    [TIMEZONE]                    VARCHAR (MAX) NULL,
    [CC]                          VARCHAR (MAX) NULL,
    [REGION]                      VARCHAR (MAX) NULL,
    [LAST_CHANGED]                DATETIME      NULL,
    [LEID]                        BIGINT        NULL,
    [EUID]                        VARCHAR (MAX) NULL,
    [NOTES]                       FLOAT (53)    NULL,
    [TAGS]                        VARCHAR (MAX) NULL
);

